import type { Metadata } from 'next'

import ReactQueryProvider from '../react-query/provider/ReactQueryProvider'

export const metadata: Metadata = {
  title: 'Tanstack React Query',
  description: 'Generated by create next app',
}

export default function TanstackLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  )
}
