import type { Metadata } from 'next'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import ReactQueryProvider from '../react-query/provider/ReactQueryProvider'

export const metadata: Metadata = {
  title: 'Tanstack React Query',
  description: 'Generated by create next app',
}

export default function TanstackLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <ReactQueryProvider>
          <NuqsAdapter>{children}</NuqsAdapter>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
